"""Pydantic schemas package."""

from app.schemas.application import (
    ApplicationCreate,
    ApplicationResponse,
    ApplicationUpdate,
)
from app.schemas.auth import (
    TokenPayload,
    TokenResponse,
    UserLoginRequest,
    UserRegisterRequest,
    UserResponse,
)
from app.schemas.candidate import (
    CandidateDashboardResponse,
    CandidateEducationCreate,
    CandidateEducationResponse,
    CandidateEducationUpdate,
    CandidateExperienceCreate,
    CandidateExperienceResponse,
    CandidateExperienceUpdate,
    CandidateProfileRead,
    CandidateResumeResponse,
    CandidateResumeUploadRequest,
    CandidateSkillCreate,
    CandidateSkillResponse,
    CandidateSkillUpdate,
    ProfileCompletenessResponse,
)
from app.schemas.candidate import (
    CandidateProfileUpdate as CandidateProfileUpdateRequest,
)
from app.schemas.career_copilot import (
    CareerCopilotChatResult,
    CareerCopilotRequest,
    CareerCopilotResponse,
    CopilotConversationResponse,
    CopilotConversationSummary,
    CopilotMessageResponse,
)
from app.schemas.course import (
    CourseCreate,
    CourseResponse,
    CourseSkillRequirement,
    CourseSkillResponse,
    CourseUpdate,
)
from app.schemas.employer import (
    EmployerApplicationCandidateInfo,
    EmployerApplicationResponse,
    EmployerApplicationStatusUpdate,
    EmployerDashboardMetrics,
    EmployerDashboardResponse,
    EmployerRecentApplicationItem,
    EmployerRecentJobItem,
)
from app.schemas.enrollment import (
    EnrollmentCreate,
    EnrollmentResponse,
    EnrollmentUpdate,
)
from app.schemas.health import HealthResponse
from app.schemas.job import (
    JobCreate,
    JobResponse,
    JobSkillRequirement,
    JobSkillResponse,
    JobUpdate,
)
from app.schemas.profiles import (
    CandidateProfileCreate,
    CandidateProfileResponse,
    CandidateProfileUpdate,
    EmployerProfileCreate,
    EmployerProfileResponse,
    EmployerProfileUpdate,
    GovernmentProfileCreate,
    GovernmentProfileResponse,
    GovernmentProfileUpdate,
    TrainingProviderProfileCreate,
    TrainingProviderProfileResponse,
    TrainingProviderProfileUpdate,
)
from app.schemas.semantic import (
    EmbeddingStatusResponse,
    MatchType,
    SemanticMatchItem,
    SemanticMatchRequest,
    SemanticMatchResponse,
)
from app.schemas.skill import (
    SkillAliasCreate,
    SkillAliasResponse,
    SkillCatalogItem,
    SkillCreate,
    SkillDetailResponse,
    SkillRelationshipCreate,
    SkillRelationshipResponse,
    SkillResponse,
    SkillUpdate,
)
from app.schemas.skill_gap import (
    GapSeverity,
    SkillGapItem,
    SkillGapReport,
    SkillGapStatus,
    SkillGapSummary,
)

__all__ = [
    "ApplicationCreate",
    "ApplicationResponse",
    "ApplicationUpdate",
    "CandidateDashboardResponse",
    "CandidateEducationCreate",
    "CandidateEducationResponse",
    "CandidateEducationUpdate",
    "CandidateExperienceCreate",
    "CandidateExperienceResponse",
    "CandidateExperienceUpdate",
    "CandidateProfileCreate",
    "CandidateProfileRead",
    "CandidateProfileResponse",
    "CandidateProfileUpdate",
    "CandidateProfileUpdateRequest",
    "CandidateResumeResponse",
    "CandidateResumeUploadRequest",
    "CandidateSkillCreate",
    "CandidateSkillResponse",
    "CandidateSkillUpdate",
    "CareerCopilotChatResult",
    "CareerCopilotRequest",
    "CareerCopilotResponse",
    "CopilotConversationResponse",
    "CopilotConversationSummary",
    "CopilotMessageResponse",
    "CourseCreate",
    "CourseResponse",
    "CourseSkillRequirement",
    "CourseSkillResponse",
    "CourseUpdate",
    "EmployerApplicationCandidateInfo",
    "EmployerApplicationResponse",
    "EmployerApplicationStatusUpdate",
    "EmployerDashboardMetrics",
    "EmployerDashboardResponse",
    "EmployerProfileCreate",
    "EmployerProfileResponse",
    "EmployerProfileUpdate",
    "EmployerRecentApplicationItem",
    "EmployerRecentJobItem",
    "EmbeddingStatusResponse",
    "EnrollmentCreate",
    "EnrollmentResponse",
    "EnrollmentUpdate",
    "GapSeverity",
    "GovernmentProfileCreate",
    "GovernmentProfileResponse",
    "GovernmentProfileUpdate",
    "HealthResponse",
    "JobCreate",
    "JobResponse",
    "JobSkillRequirement",
    "JobSkillResponse",
    "JobUpdate",
    "MatchType",
    "ProfileCompletenessResponse",
    "SemanticMatchItem",
    "SemanticMatchRequest",
    "SemanticMatchResponse",
    "SkillAliasCreate",
    "SkillAliasResponse",
    "SkillCatalogItem",
    "SkillCreate",
    "SkillDetailResponse",
    "SkillGapItem",
    "SkillGapReport",
    "SkillGapStatus",
    "SkillGapSummary",
    "SkillRelationshipCreate",
    "SkillRelationshipResponse",
    "SkillResponse",
    "SkillUpdate",
    "TokenPayload",
    "TokenResponse",
    "TrainingProviderProfileCreate",
    "TrainingProviderProfileResponse",
    "TrainingProviderProfileUpdate",
    "UserLoginRequest",
    "UserRegisterRequest",
    "UserResponse",
]
